server:
  port: 9445
security:
  jwt:
    key-store-file: authKeyStore.jks
    key-store-type: PKCS12
    key-store-alias: auth
    key-store-password: mti!QCh5e
    issuer: http://localhost:9445
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: lorice123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl