DROP SCHEMA IF EXISTS AUTH;

CREATE SCHEMA IF NOT EXISTS AUTH DEFAULT CHARACTER SET utf8;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

USE AUTH;

CREATE TABLE IF NOT EXISTS OAUTH_CLIENT_DETAILS (
	CLIENT_ID VARCHAR(256) NOT NULL,
	CLIENT_SECRET VARCHAR(256) NOT NULL,
	WEB_SERVER_REDIRECT_URI VARCHAR(2048) DEFAULT NULL,
	SCOPE VARCHAR(256) DEFAULT NULL,
	ACCESS_TOKEN_VALIDITY INT(11) DEFAULT NULL,
	REFRESH_TOKEN_VALIDITY INT(11) DEFAULT NULL,
	RESOURCE_IDS VARCHAR(1024) DEFAULT NULL,
	AUTHORIZED_GRANT_TYPES VARCHAR(1024) DEFAULT NULL,
	AUTHORITIES VARCHAR(1024) DEFAULT NULL,
	ADDITIONAL_INFORMATION VARCHAR(4096) DEFAULT NULL,
	AUTOAPPROVE VARCHAR(256) DEFAULT NULL,
	PRIMARY KEY (CLIENT_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS USER (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(1024) NOT NULL,
	EMAIL VARCHAR(1024),
	ENABLED TINYINT(4) NOT NULL,
	ACCOUNTNONEXPIRED TINYINT(4) NOT NULL,
	CREDENTIALSNONEXPIRED TINYINT(4) NOT NULL,
	ACCOUNTNONLOCKED TINYINT(4) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE KEY USERNAME (USERNAME)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS ROLE (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(256) DEFAULT NULL,
	PRIMARY KEY (ID),
	UNIQUE KEY NAME (NAME)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS ROLE_USER (
	ROLE_ID INT(11) DEFAULT NULL,
	USER_ID INT(11) DEFAULT NULL,
	KEY ROLE_ID (ROLE_ID),
	KEY USER_ID (USER_ID),
	CONSTRAINT ROLE_USER_IBFK_1 FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID),
	CONSTRAINT ROLE_USER_IBFK_2 FOREIGN KEY (USER_ID) REFERENCES USER (ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS PERMISSION (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(512) DEFAULT NULL,
	PRIMARY KEY (ID),
	UNIQUE KEY NAME (NAME)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS PERMISSION_ROLE (
	PERMISSION_ID INT(11) DEFAULT NULL,
	ROLE_ID INT(11) DEFAULT NULL,
	KEY PERMISSION_ID (PERMISSION_ID),
	KEY ROLE_ID (ROLE_ID),
	CONSTRAINT PERMISSION_ROLE_IBFK_1 FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION (ID),
	CONSTRAINT PERMISSION_ROLE_IBFK_2 FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
) ENGINE=INNODB;

-- TOKEN STORE
CREATE TABLE IF NOT EXISTS OAUTH_CLIENT_TOKEN (
	TOKEN_ID VARCHAR(256),
	TOKEN LONG VARBINARY,
	AUTHENTICATION_ID VARCHAR(256) PRIMARY KEY,
	USER_NAME VARCHAR(256),
	CLIENT_ID VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS OAUTH_ACCESS_TOKEN (
	TOKEN_ID VARCHAR(256),
	TOKEN LONG VARBINARY,
	AUTHENTICATION_ID VARCHAR(256) PRIMARY KEY,
	USER_NAME VARCHAR(256),
	CLIENT_ID VARCHAR(256),
	AUTHENTICATION LONG VARBINARY,
	REFRESH_TOKEN VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS OAUTH_REFRESH_TOKEN (
	TOKEN_ID VARCHAR(256),
	TOKEN LONG VARBINARY,
	AUTHENTICATION LONG VARBINARY
);

CREATE TABLE IF NOT EXISTS OAUTH_CODE (
	CODE VARCHAR(256),
	AUTHENTICATION LONG VARBINARY
);

CREATE TABLE IF NOT EXISTS OAUTH_APPROVALS (
	USERID VARCHAR(256),
	CLIENTID VARCHAR(256),
	SCOPE VARCHAR(256),
	STATUS VARCHAR(10),
	EXPIRESAT TIMESTAMP,
	LASTMODIFIEDAT TIMESTAMP
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;